version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/carpe_caelum_api"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/carpe-caelum-frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
