# sig/weather_snapshot.rbs

class WeatherSnapshot
  attr_reader utc: Time
  attr_reader temperature_apparent: Float?
  attr_reader weather_description: String

  def initialize: (utc: Time, temperature_apparent: Float?, weather_description: String) -> void
end
