# sig/weather_snapshot_collection.rbs

class WeatherSnapshotCollection
  attr_reader weather_snapshots: Hash[String, WeatherSnapshot]

  def initialize: (weather_snapshots: Hash[String, WeatherSnapshot]) -> void
  def temp_high: () -> Float?
  def temp_low: () -> Float?
  def utc_start: () -> String?
  def utc_end: () -> String?
  def list_of_snapshots: () -> Array[WeatherSnapshot]
  def weather_snapshot_for: (utc: String) -> WeatherSnapshot?
end
