# typed: true

class WeatherFactory
  def self.build_weather_snapshots_from_tomorrow_io_timeline_resp: (Hash[String, untyped]) -> WeatherSnapshotCollection
  def self.build_weather_snapshot_from_tomorrow_io_timeline_interval: (api_response_interval: Hash[String, untyped]) -> WeatherSnapshot

  private

  def self.translate_tomorrow_io_weather_code_to_weather_description: (String) -> WeatherDescriptions?
end

