source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# Rails
gem 'rails', '~> 7.1.3'

# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'

# Use Puma as the app server
gem 'puma', '~> 6.0'

# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
gem 'image_processing', '~> 1.2'

# Authentication
gem 'devise'

# GraphQL
gem 'graphql'
gem 'graphiql-rails', group: :development

# Redis for caching
gem 'redis'

# Dotenv for environment variables
gem 'dotenv-rails', groups: [:development, :test]

# CORS
gem 'rack-cors'

# Debugging tools
gem 'pry-rails', group: [:development, :test]

# Bootsnap for speeding up boot time
gem 'bootsnap', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'pry'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Use Active Record's built-in test framework
gem 'minitest', group: :test

# Use factory_bot for fixtures replacement
gem 'factory_bot_rails', group: :test

# Use Faker for generating fake data
gem 'faker', group: :test

# JSON Web Tokens (JWT) for authentication
gem 'jwt'

gem 'rbs'
gem 'steep'


gem 'net-http-persistent'
