source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '~> 7.1.3'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 6.0'
gem 'bcrypt', '~> 3.1.7'
gem 'image_processing', '~> 1.2'
gem 'devise'
gem 'graphql'
gem 'redis'
gem 'rack-cors'
gem 'bootsnap', require: false
gem 'jwt'
gem 'rbs'
gem 'steep'
gem 'net-http-persistent'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'pry'
  gem 'rspec-rails', '~> 5.0'
  gem 'factory_bot_rails'
  gem 'pry-rails'
  gem 'dotenv-rails'
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'spring'
  gem 'graphiql-rails'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'shoulda-matchers', '~> 5.0'
  gem 'faker'
  gem 'minitest'
  gem 'simplecov'
end
