# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', require: false
gem 'devise'
gem 'graphql'
gem 'image_processing', '~> 1.2'
gem 'jwt'
gem 'net-http-persistent'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 6.0'
gem 'rack-cors'
gem 'rails', '~> 7.1.3'
gem 'rbs'
gem 'redis'
gem 'steep'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'capybara', '>= 3.26'
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'pry'
  gem 'pry-rails'
  gem 'rails_best_practices', require: false
  gem 'rspec-rails', '~> 6.1'
  gem 'rubocop', require: false
  gem 'rubocop-capybara', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-graphql', require: false
  gem 'rubocop-minitest', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-rspec_rails', require: false
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

group :development do
  gem 'graphiql-rails'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.1.0'
  gem 'web-console', '>= 4.1.0'
end

group :test do
  gem 'faker'
  gem 'minitest'
  gem 'shoulda-matchers', '~> 6.2'
  gem 'simplecov'
end
