name: CI

permissions:
  contents: write
  packages: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Cache for Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Set up Cache for Node Modules
        uses: actions/cache@v3
        with:
          path: carpe-caelum-frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

  test-backend:
    runs-on: ubuntu-latest
    needs: setup

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: carpe_caelum_test

      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      RAILS_ENV: test
      PGHOST: localhost
      CARPE_CAELUM_DATABASE_USERNAME: postgres
      CARPE_CAELUM_DATABASE_PASSWORD: password
      PGDATABASE: carpe_caelum_test

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Install backend dependencies
        run: |
          cd carpe_caelum_api
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Set up Database
        run: |
          cd carpe_caelum_api
          bin/rails db:create
          bin/rails db:migrate

      - name: Run backend tests and generate coverage report
        run: |
          cd carpe_caelum_api
          SIMPLECOV=true bundle exec rspec

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage-report
          path: carpe_caelum_api/coverage/

  test-frontend:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd carpe-caelum-frontend
          npm install

      - name: Run frontend lint
        run: |
          cd carpe-caelum-frontend
          npm run lint
